export default {
  // Fetch clients
  CLIENTS_GET_REQUEST: 'CLIENTS_GET_REQUEST',
  CLIENTS_GET_SUCCESS: 'CLIENTS_GET_SUCCESS',
  CLIENTS_GET_FAIL: 'CLIENTS_GET_FAIL',

  // Create client
  CLIENT_CREATE_REQUEST: 'CLIENT_CREATE_REQUEST',
  CLIENT_CREATE_SUCCESS: 'CLIENT_CREATE_SUCCESS',
  CLIENT_CREATE_FAIL: 'CLIENT_CREATE_FAIL',

  // Update client
  CLIENT_UPDATE_REQUEST: 'CLIENT_UPDATE_REQUEST',
  CLIENT_UPDATE_SUCCESS: 'CLIENT_UPDATE_SUCCESS',
  CLIENT_UPDATE_FAIL: 'CLIENT_UPDATE_FAIL',

  // Delete client
  CLIENT_DELETE_REQUEST: 'CLIENT_DELETE_REQUEST',
  CLIENT_DELETE_SUCCESS: 'CLIENT_DELETE_SUCCESS',
  CLIENT_DELETE_FAIL: 'CLIENT_DELETE_FAIL',

  // Set client
  CLIENT_SET: 'CLIENT_SET',

  // Set client type
  CLIENT_SET_TYPE: 'CLIENT_SET_TYPE',

  // Set client product view type
  CLIENT_SET_PRODUCT_VIEW_TYPE: 'CLIENT_SET_PRODUCT_VIEW_TYPE',

  // Fetch categories
  CATEGORIES_GET_REQUEST: 'CATEGORIES_GET_REQUEST',
  CATEGORIES_GET_SUCCESS: 'CATEGORIES_GET_SUCCESS',
  CATEGORIES_GET_FAIL: 'CATEGORIES_GET_FAIL',

  // Create category
  CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
  CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
  CATEGORY_CREATE_FAIL: 'CATEGORY_CREATE_FAIL',

  // Update category
  CATEGORY_UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUEST',
  CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
  CATEGORY_UPDATE_FAIL: 'CATEGORY_UPDATE_FAIL',

  // Delete category
  CATEGORY_DELETE_REQUEST: 'CATEGORY_DELETE_REQUEST',
  CATEGORY_DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
  CATEGORY_DELETE_FAIL: 'CATEGORY_DELETE_FAIL',

  // Set category
  CATEGORY_SET: 'CATEGORY_SET',
  // Set category
  TREE_SET: 'TREE_SET',

  // Create PropertyFields
  PROPERTY_FIELD_CREATE_REQUEST: 'PROPERTY_FIELD_CREATE_REQUEST',
  PROPERTY_FIELD_CREATE_SUCCESS: 'PROPERTY_FIELD_CREATE_SUCCESS',
  PROPERTY_FIELD_CREATE_FAIL: 'PROPERTY_FIELD_CREATE_FAIL',

  // Fetch PropertyFields
  PROPERTY_FIELD_GET_REQUEST: 'PROPERTY_FIELD_GET_REQUEST',
  PROPERTY_FIELD_GET_SUCCESS: 'PROPERTY_FIELD_GET_SUCCESS',
  PROPERTY_FIELD_GET_FAIL: 'PROPERTY_FIELD_GET_FAIL',

  // Update PropertyFields
  PROPERTY_FIELD_UPDATE_REQUEST: 'PROPERTY_FIELD_UPDATE_REQUEST',
  PROPERTY_FIELD_UPDATE_SUCCESS: 'PROPERTY_FIELD_UPDATE_SUCCESS',
  PROPERTY_FIELD_UPDATE_FAIL: 'PROPERTY_FIELD_UPDATE_FAIL',

  // Delete PropertyFields
  PROPERTY_FIELD_DELETE_REQUEST: 'PROPERTY_FIELD_DELETE_REQUEST',
  PROPERTY_FIELD_DELETE_SUCCESS: 'PROPERTY_FIELD_DELETE_SUCCESS',
  PROPERTY_FIELD_DELETE_FAIL: 'PROPERTY_FIELD_DELETE_FAIL',

  // Get Products Data
  PRODUCTS_GET_DATA_REQUEST: 'PRODUCTS_GET_DATA_REQUEST',
  PRODUCTS_GET_DATA_SUCCESS: 'PRODUCTS_GET_DATA_SUCCESS',
  PRODUCTS_GET_DATA_FAIL: 'PRODUCTS_GET_DATA_FAIL',

  // Get Products Data
  PRODUCTS_GET_LENGTH_REQUEST: 'PRODUCTS_GET_LENGTH_REQUEST',
  PRODUCTS_GET_LENGTH_SUCCESS: 'PRODUCTS_GET_LENGTH_SUCCESS',
  PRODUCTS_GET_LENGTH_FAIL: 'PRODUCTS_GET_LENGTH_FAIL',

  // Update Products Data
  PRODUCTS_UPDATE_REQUEST: 'PRODUCTS_UPDATE_REQUEST',
  PRODUCTS_UPDATE_SUCCESS: 'PRODUCTS_UPDATE_SUCCESS',
  PRODUCTS_UPDATE_FAIL: 'PRODUCTS_UPDATE_FAIL',

  // Set Products Data
  PRODUCTS_SET_PRODUCTS: 'PRODUCTS_SET_PRODUCTS',
  // Set Products Data
  PRODUCTS_SET_UPDATE_PRODUCTS: 'PRODUCTS_SET_UPDATE_PRODUCTS',
  // Set Image Key
  PRODUCTS_SET_IMAGEKEY_SUCCESS: 'PRODUCTS_SET_IMAGEKEY_SUCCESS',
  PRODUCTS_SET_IMAGEKEY_REQEUST: 'PRODUCTS_SET_IMAGEKEY_REQEUST',
  PRODUCTS_SET_IMAGEKEY_ERROR: 'PRODUCTS_SET_IMAGEKEY_ERROR',
  // Get Products Fields
  PRODUCTS_GET_FIELDS_REQUEST: 'PRODUCTS_GET_FIELDS_REQUEST',
  PRODUCTS_GET_FIELDS_SUCCESS: 'PRODUCTS_GET_FIELDS_SUCCESS',
  PRODUCTS_GET_FIELDS_FAIL: 'PRODUCTS_GET_FIELDS_FAIL',

  PRODUCTS_UPDATE_FIELDS_REQUEST: 'PRODUCTS_UPDATE_FIELDS_REQUEST',
  PRODUCTS_UPDATE_FIELDS_SUCCESS: 'PRODUCTS_UPDATE_FIELDS_SUCCESS',
  PRODUCTS_UPDATE_FIELDS_FAIL: 'PRODUCTS_UPDATE_FIELDS_FAIL',

  PRODUCTS_DELETE_FIELDS_REQUEST: 'PRODUCTS_DELETE_FIELDS_REQUEST',
  PRODUCTS_DELETE_FIELDS_SUCCESS: 'PRODUCTS_DELETE_FIELDS_SUCCESS',
  PRODUCTS_DELETE_FIELDS_FAIL: 'PRODUCTS_DELETE_FIELDS_FAIL',


  // Attributes
  ATTRIBUTE_CREATE_REQUEST: 'ATTRIBUTE_CREATE_REQUEST',
  ATTRIBUTE_CREATE_SUCCESS: 'ATTRIBUTE_CREATE_SUCCESS',
  ATTRIBUTE_CREATE_FAIL: 'ATTRIBUTE_CREATE_FAIL',


};
