export default {
  // Fetch clients
  CLIENTS_GET_REQUEST: 'CLIENTS_GET_REQUEST',
  CLIENTS_GET_SUCCESS: 'CLIENTS_GET_SUCCESS',
  CLIENTS_GET_FAIL: 'CLIENTS_GET_FAIL',

  // Create client
  CLIENT_CREATE_REQUEST: 'CLIENT_CREATE_REQUEST',
  CLIENT_CREATE_SUCCESS: 'CLIENT_CREATE_SUCCESS',
  CLIENT_CREATE_FAIL: 'CLIENT_CREATE_FAIL',

  // Update client
  CLIENT_UPDATE_REQUEST: 'CLIENT_UPDATE_REQUEST',
  CLIENT_UPDATE_SUCCESS: 'CLIENT_UPDATE_SUCCESS',
  CLIENT_UPDATE_FAIL: 'CLIENT_UPDATE_FAIL',

  // Delete client
  CLIENT_DELETE_REQUEST: 'CLIENT_DELETE_REQUEST',
  CLIENT_DELETE_SUCCESS: 'CLIENT_DELETE_SUCCESS',
  CLIENT_DELETE_FAIL: 'CLIENT_DELETE_FAIL',

  // Set client
  CLIENT_SET: 'CLIENT_SET',

  // Set client type
  CLIENT_SET_TYPE: 'CLIENT_SET_TYPE',

  // Set client product view type
  CLIENT_SET_PRODUCT_VIEW_TYPE: 'CLIENT_SET_PRODUCT_VIEW_TYPE',

  // Fetch categories
  CATEGORIES_GET_REQUEST: 'CATEGORIES_GET_REQUEST',
  CATEGORIES_GET_SUCCESS: 'CATEGORIES_GET_SUCCESS',
  CATEGORIES_GET_FAIL: 'CATEGORIES_GET_FAIL',

  // Create category
  CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
  CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
  CATEGORY_CREATE_FAIL: 'CATEGORY_CREATE_FAIL',

  // Update category
  CATEGORY_UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUEST',
  CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
  CATEGORY_UPDATE_FAIL: 'CATEGORY_UPDATE_FAIL',

  // Delete category
  CATEGORY_DELETE_REQUEST: 'CATEGORY_DELETE_REQUEST',
  CATEGORY_DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
  CATEGORY_DELETE_FAIL: 'CATEGORY_DELETE_FAIL',

  // Set category
  CATEGORY_SET: 'CATEGORY_SET',
  // Set category
  TREE_SET: 'TREE_SET',

  // Update the default on categories
  CATEGORY_UPDATE_DEFAULT_REQUEST: 'CATEGORY_UPDATE_DEFAULT_REQUEST',
  CATEGORY_UPDATE_DEFAULT_SUCCESS: 'CATEGORY_UPDATE_DEFAULT_SUCCESS',
  CATEGORY_UPDATE_DEFAULT_FAIL: 'CATEGORY_UPDATE_DEFAULT_FAIL',
  // Set matched products
  MATCHED_PRODUCT: 'MATCHED_PRODUCT',

  // Create PropertyFields
  PROPERTY_FIELD_CREATE_REQUEST: 'PROPERTY_FIELD_CREATE_REQUEST',
  PROPERTY_FIELD_CREATE_SUCCESS: 'PROPERTY_FIELD_CREATE_SUCCESS',
  PROPERTY_FIELD_CREATE_FAIL: 'PROPERTY_FIELD_CREATE_FAIL',

  // Fetch PropertyFields
  PROPERTY_FIELD_GET_REQUEST: 'PROPERTY_FIELD_GET_REQUEST',
  PROPERTY_FIELD_GET_SUCCESS: 'PROPERTY_FIELD_GET_SUCCESS',
  PROPERTY_FIELD_GET_FAIL: 'PROPERTY_FIELD_GET_FAIL',

  // Update PropertyFields
  PROPERTY_FIELD_UPDATE_REQUEST: 'PROPERTY_FIELD_UPDATE_REQUEST',
  PROPERTY_FIELD_UPDATE_SUCCESS: 'PROPERTY_FIELD_UPDATE_SUCCESS',
  PROPERTY_FIELD_UPDATE_FAIL: 'PROPERTY_FIELD_UPDATE_FAIL',

  // Delete PropertyFields
  PROPERTY_FIELD_DELETE_REQUEST: 'PROPERTY_FIELD_DELETE_REQUEST',
  PROPERTY_FIELD_DELETE_SUCCESS: 'PROPERTY_FIELD_DELETE_SUCCESS',
  PROPERTY_FIELD_DELETE_FAIL: 'PROPERTY_FIELD_DELETE_FAIL',

  // Get Products Data
  PRODUCTS_GET_DATA_REQUEST: 'PRODUCTS_GET_DATA_REQUEST',
  PRODUCTS_GET_DATA_SUCCESS: 'PRODUCTS_GET_DATA_SUCCESS',
  PRODUCTS_GET_DATA_FAIL: 'PRODUCTS_GET_DATA_FAIL',

  // Get Products Data
  PRODUCTS_GET_LENGTH_REQUEST: 'PRODUCTS_GET_LENGTH_REQUEST',
  PRODUCTS_GET_LENGTH_SUCCESS: 'PRODUCTS_GET_LENGTH_SUCCESS',
  PRODUCTS_GET_LENGTH_FAIL: 'PRODUCTS_GET_LENGTH_FAIL',

  // Update Products Data
  PRODUCTS_UPDATE_REQUEST: 'PRODUCTS_UPDATE_REQUEST',
  PRODUCTS_UPDATE_SUCCESS: 'PRODUCTS_UPDATE_SUCCESS',
  PRODUCTS_UPDATE_FAIL: 'PRODUCTS_UPDATE_FAIL',

  // Set Products Data
  PRODUCTS_SET_PRODUCTS: 'PRODUCTS_SET_PRODUCTS',
  // Set Products Data
  PRODUCTS_SET_UPDATE_PRODUCTS: 'PRODUCTS_SET_UPDATE_PRODUCTS',
  // Set Image Key
  PRODUCTS_SET_IMAGEKEY_SUCCESS: 'PRODUCTS_SET_IMAGEKEY_SUCCESS',
  PRODUCTS_SET_IMAGEKEY_REQEUST: 'PRODUCTS_SET_IMAGEKEY_REQEUST',
  PRODUCTS_SET_IMAGEKEY_ERROR: 'PRODUCTS_SET_IMAGEKEY_ERROR',
  // Set Hover Size
  PRODUCTS_HOVER_SIZE: 'PRODUCTS_HOVER_SIZE',
  // Get Products Fields
  PRODUCTS_GET_FIELDS_REQUEST: 'PRODUCTS_GET_FIELDS_REQUEST',
  PRODUCTS_GET_FIELDS_SUCCESS: 'PRODUCTS_GET_FIELDS_SUCCESS',
  PRODUCTS_GET_FIELDS_FAIL: 'PRODUCTS_GET_FIELDS_FAIL',

  PRODUCTS_UPDATE_FIELDS_REQUEST: 'PRODUCTS_UPDATE_FIELDS_REQUEST',
  PRODUCTS_UPDATE_FIELDS_SUCCESS: 'PRODUCTS_UPDATE_FIELDS_SUCCESS',
  PRODUCTS_UPDATE_FIELDS_FAIL: 'PRODUCTS_UPDATE_FIELDS_FAIL',

  PRODUCTS_DELETE_FIELDS_REQUEST: 'PRODUCTS_DELETE_FIELDS_REQUEST',
  PRODUCTS_DELETE_FIELDS_SUCCESS: 'PRODUCTS_DELETE_FIELDS_SUCCESS',
  PRODUCTS_DELETE_FIELDS_FAIL: 'PRODUCTS_DELETE_FIELDS_FAIL',

  // Update All Product field
  PRODUCTS_UPDATE_ALL_REQUEST: 'PRODUCTS_UPDATE_ALL_REQUEST',
  PRODUCTS_UPDATE_ALL_SUCCESS: 'PRODUCTS_UPDATE_ALL_SUCCESS',
  PRODUCTS_UPDATE_ALL_FAIL: 'PRODUCTS_UPDATE_ALL_FAIL',

  // Attributes
  ATTRIBUTE_CREATE_REQUEST: 'ATTRIBUTE_CREATE_REQUEST',
  ATTRIBUTE_CREATE_SUCCESS: 'ATTRIBUTE_CREATE_SUCCESS',
  ATTRIBUTE_CREATE_FAIL: 'ATTRIBUTE_CREATE_FAIL',

  ATTRIBUTE_FETCH_REQUEST: 'ATTRIBUTE_FETCH_REQUEST',
  ATTRIBUTE_FETCH_SUCCESS: 'ATTRIBUTE_FETCH_SUCCESS',
  ATTRIBUTE_FETCH_FAIL: 'ATTRIBUTE_FETCH_FAIL',

  ATTRIBUTE_UPDATE_REQUEST: 'ATTRIBUTE_UPDATE_REQUEST',
  ATTRIBUTE_UPDATE_SUCCESS: 'ATTRIBUTE_UPDATE_SUCCESS',
  ATTRIBUTE_UPDATE_FAIL: 'ATTRIBUTE_UPDATE_FAIL',

  ATTRIBUTE_REMOVE_REQUEST: 'ATTRIBUTE_REMOVE_REQUEST',
  ATTRIBUTE_REMOVE_SUCCESS: 'ATTRIBUTE_REMOVE_SUCCESS',
  ATTRIBUTE_REMOVE_FAIL: 'ATTRIBUTE_REMOVE_FAIL',

  ATTRIBUTE_NODE_SET: 'ATTRIBUTE_NODE_SET',

  ATTRIBUTE_SET: 'ATTRIBUTE_SET',

  // Handle Appear
  ATTRIBUTE_UPDATE_APPEAR_REQUEST: 'ATTRIBUTE_UPDATE_APPEAR_REQUEST',
  ATTRIBUTE_UPDATE_APPEAR_SUCCESS: 'ATTRIBUTE_UPDATE_APPEAR_SUCCESS',
  ATTRIBUTE_UPDATE_APPEAR_FAIL: 'ATTRIBUTE_UPDATE_APPEAR_FAIL',

  ATTRIBUTE_REMOVE_APPEAR_REQUEST: 'ATTRIBUTE_REMOVE_APPEAR_REQUEST',
  ATTRIBUTE_REMOVE_APPEAR_SUCCESS: 'ATTRIBUTE_REMOVE_APPEAR_SUCCESS',
  ATTRIBUTE_REMOVE_APPEAR_FAIL: 'ATTRIBUTE_REMOVE_APPEAR_FAIL',

  // Update Default value
  ATTRIBUTE_UPDATE_DEFAULT_REQUEST: 'ATTRIBUTE_UPDATE_DEFAULT_REQUEST',
  ATTRIBUTE_UPDATE_DEFAULT_SUCCESS: 'ATTRIBUTE_UPDATE_DEFAULT_SUCCESS',
  ATTRIBUTE_UPDATE_DEFAULT_FAIL: 'ATTRIBUTE_UPDATE_DEFAULT_FAIL',
  // History
  HISTORY_CREATE_REQUEST: 'HISTORY_CREATE_REQUEST',
  HISTORY_CREATE_SUCCESS: 'HISTORY_CREATE_SUCCESS',
  HISTORY_CREATE_FAIL: 'HISTORY_CREATE_FAIL',

  HISTORY_FETCH_REQUEST: 'HISTORY_FETCH_REQUEST',
  HISTORY_FETCH_SUCCESS: 'HISTORY_FETCH_SUCCESS',
  HISTORY_FETCH_FAIL: 'HISTORY_FETCH_FAIL',

  HISTORY_UPDATE_REQUEST: 'HISTORY_UPDATE_REQUEST',
  HISTORY_UPDATE_SUCCESS: 'HISTORY_UPDATE_SUCCESS',
  HISTORY_UPDATE_FAIL: 'HISTORY_UPDATE_FAIL',

  HISTORY_REMOVE_REQUEST: 'HISTORY_REMOVE_REQUEST',
  HISTORY_REMOVE_SUCCESS: 'HISTORY_REMOVE_SUCCESS',
  HISTORY_REMOVE_FAIL: 'HISTORY_REMOVE_FAIL',

  // UPLOAD
  UPLOAD_DATA_REQUEST: 'UPLOAD_DATA_REQUEST',
  UPLOAD_DATA_SUCCESS: 'UPLOAD_DATA_SUCCESS',
  UPLOAD_DATA_FAIL: 'UPLOAD_DATA_FAIL',

  UPLOAD_KEY_DATA_REQUEST: 'UPLOAD_KEY_DATA_REQUEST',
  UPLOAD_KEY_DATA_SUCCESS: 'UPLOAD_KEY_DATA_SUCCESS',
  UPLOAD_KEY_DATA_FAIL: 'UPLOAD_KEY_DATA_FAIL',

  // PREVIEW
  SET_PREVIEW_CATEGORY: 'SET_PREVIEW_CATEGORY',
  SET_ROOT_CATEGORY: 'SET_ROOT_CATEGORY',
  SET_URL_PATH_NAV: 'SET_URL_PATH_NAV',
  MOVE_POINTED_PATH: 'MOVE_POINTED_PATH',
};
